In [1]:
import os
import shutil
import glob
import numpy as np
import pandas as pd

In [8]:
for curDir, dirs, files in os.walk('.'):
    for file in files:
        print(os.path.abspath(f'{curDir}/{file}'))

C:\Users\hatayuki\OneDrive - The University of Tokyo\now_using\210905\Untitled.ipynb
C:\Users\hatayuki\OneDrive - The University of Tokyo\now_using\210905\.ipynb_checkpoints\Untitled-checkpoint.ipynb
C:\Users\hatayuki\OneDrive - The University of Tokyo\now_using\210905\Al\100\results.txt
C:\Users\hatayuki\OneDrive - The University of Tokyo\now_using\210905\Al\110\results.txt
C:\Users\hatayuki\OneDrive - The University of Tokyo\now_using\210905\Al\111\results.txt
C:\Users\hatayuki\OneDrive - The University of Tokyo\now_using\210905\Cu\100\results.txt
C:\Users\hatayuki\OneDrive - The University of Tokyo\now_using\210905\Cu\110\results.txt
C:\Users\hatayuki\OneDrive - The University of Tokyo\now_using\210905\Cu\111\results.txt
C:\Users\hatayuki\OneDrive - The University of Tokyo\now_using\210905\Fe\100\results.txt
C:\Users\hatayuki\OneDrive - The University of Tokyo\now_using\210905\Fe\110\results.txt
C:\Users\hatayuki\OneDrive - The University of Tokyo\now_using\210905\Fe\111\results.txt

In [4]:
os.chdir('fcc')
os.getcwd()

'E:\\CNIDs_GB_area_gbnum\\fcc'

In [31]:
# results までのディレクトリを複製する関数(元素のフォルダの親ディレクトリまで移動して実行)
basedir = 'C:\\Users\\hatayuki\\OneDrive - The University of Tokyo\\now_using\\database'
for name in glob.glob('./**/*results.txt', recursive=True):
#     category = '\\'.join(name.split('\\')[:-1])
#     new_folder = f'new_files\\{category}'
    gbnum = name.split('_')[-1]
    gbnum = gbnum.split('.')[0]
    gbnum = gbnum.zfill(3)    
    category = '\\'.join(name.split('\\')[:-2])
    new_folder = f'{basedir}\\new_files\\{category}\\{gbnum}'
    os.makedirs(new_folder,exist_ok=True)
    shutil.copy(f'{name}',f'{new_folder}')

In [32]:
for name in glob.glob('./**/*CNIDs', recursive=True):
    category = '\\'.join(name.split('\\')[:-1])
    new_folder = f'{filename}\\{category}'
    os.makedirs(new_folder,exist_ok=True)
    shutil.copy(f'{name}',f'{new_folder}')

In [33]:
os.chdir('now_using/')
os.getcwd()

'C:\\Users\\hatay\\OneDrive - The University of Tokyo\\now_using'

In [35]:
os.chdir('new_files')

In [52]:
df = pd.read_csv('bcc_hkl_angle.csv',index_col = 0)
bcc_hkl_angle = df.values
print(bcc_hkl_angle)

[['<0 1 2>' 53.13010235]
 ['<0 3 1>' 36.86989765]
 ['<0 2 3>' 67.38013505]
 ['<0 -1 5>' 22.61986495]
 ['<0 4 1>' 28.07248694]
 ['<0 5 -3>' 61.92751306]
 ['<0 4 -3>' 73.73979529]
 ['<0 7 1>' 16.26020471]
 ['<0 5 2>' 43.60281897]
 ['<0 3 7>' 46.39718103]
 ['<0 6 1>' 18.92464442]
 ['<0 7 -5>' 71.07535558]
 ['<0 4 5>' 77.31961651]
 ['<0 -1 9>' 12.68038349]
 ['<0 7 2>' 31.8907918]
 ['<0 5 9>' 58.1092082]
 ['<0 6 -5>' 79.61114218]
 ['<0 11 1>' 10.38885782]
 ['<0 8 1>' 14.2500327]
 ['<0 9 -7>' 75.7499673]
 ['<0 8 3>' 41.11209044]
 ['<0 5 11>' 48.88790956]
 ['<0 6 7>' 81.20258929]
 ['<0 -1 13>' 8.79741071]
 ['<0 8 -5>' 64.01076642]
 ['<0 -3 13>' 25.98923358]
 ['<0 4 9>' 47.92497795]
 ['<0 -5 13>' 42.07502205]
 ['<-1 1 1>' 70.52877937]
 ['<1 -1 2>' 109.4712206]
 ['<-2 2 1>' 38.94244127]
 ['<1 -1 4>' 141.0575587]
 ['<1 -1 3>' 129.5211964]
 ['<-3 3 2>' 50.47880364]
 ['<2 -2 3>' 93.37228668]
 ['<-3 3 4>' 86.62771332]
 ['<-3 3 1>' 26.52535202]
 ['<1 -1 6>' 153.474648]
 ['<1 -1 5>' 148.4136619]
 ['<

In [65]:
CNIDs_list = np.full(12,0)
for name in glob.glob('./**/*CNIDs', recursive=True):
    CNIDs = np.loadtxt(os.path.abspath(name))
    CNIDs = np.hstack((bcc_hkl_angle, CNIDs))
    CNIDs_list = np.vstack((CNIDs_list,CNIDs))
    
CNIDs_list = np.delete(CNIDs_list,0,axis = 0)

In [ ]:
# Xieのlammpsのファイルを作るときにindexを作っていたからそれを参考に！ 

In [66]:
print(CNIDs_list)

[['<0 1 2>' 53.13010235 2.8510001608020996 ... 5.0 1.0 1.0]
 ['<0 3 1>' 36.86989765 2.8510001608021 ... 5.0 1.0 2.0]
 ['<0 2 3>' 67.38013505 -2.851000160802099 ... 13.0 1.0 1.0]
 ...
 ['<7 4 -11>' 42.10344887 -2.4690385654481384 ... 93.0 3.0 2.0]
 ['<8 3 -11>' 30.5906886 -2.4690385654481384 ... 97.0 3.0 1.0]
 ['<19 -5 -14>' 29.4093114 -2.4690385654481384 ... 97.0 3.0 2.0]]


In [6]:
def make_gb_index(gbnum):
    vector = np.arange(1,gbnum+1) 
    vector = np.array([vector], dtype = int).T
    vector = np.array(vector, dtype = str)
    for i in range(len(vector)):
        vector[i][0] = vector[i][0].zfill(3)
    return vector

In [ ]:
# bccとfccでbcc_hkl_angleとfcc_hkl_angleで分ける
df = pd.read_csv('bcc_hkl_angle.csv', index_col= 0)
hkl_angle = df.values

In [91]:
# bcc_CNIDs_listとfcc_CNIDs_list
CNIDs_list = np.full(18,0)
for name in glob.glob('./**/*CNIDs', recursive=True):
    # この書き方でCNIDsがあるファイルの前までのカテゴリ分けできる
    # ただし、この場合だとcategory_listの要素数が一つ減る
    category_list = name.split('\\')[1:-1]
    CNIDs = np.loadtxt(os.path.abspath(name))
    gb_index = make_gb_index(len(CNIDs))
    CNIDs = np.hstack((bcc_hkl_angle, CNIDs))
    CNIDs = np.hstack((gb_index,CNIDs))
    category_list = np.tile(category_list,(len(CNIDs),1))
    CNIDs = np.hstack((category_list,CNIDs))
    CNIDs = np.hstack((CNIDs,hkl_angle))
#    print(CNIDs)
    CNIDs_list = np.vstack((CNIDs_list,CNIDs))

CNIDs_list = np.delete(CNIDs_list,0,axis = 0)

In [135]:
firstLoop = True
for name in glob.glob('./**/*CNIDs', recursive=True):
    category_list = name.split('\\')[1:-1]
    CNIDs = np.loadtxt(os.path.abspath(name))
    gb_index = make_gb_index(len(CNIDs))
    CNIDs = np.hstack((bcc_hkl_angle, CNIDs))
    CNIDs = np.hstack((gb_index,CNIDs))
    category_list = np.tile(category_list,(len(CNIDs),1))
    CNIDs = np.hstack((category_list,CNIDs))
#     CNIDs = np.hstack((CNIDs,hkl_angle))
    if firstLoop:
        CNIDs_list = CNIDs
        firstLoop = False
    else:
        CNIDs_list = np.vstack((CNIDs_list,CNIDs))
print(CNIDs_list)

[['Al' '100' '001' ... 5.0 1.0 1.0]
 ['Al' '100' '001' ... 5.0 1.0 2.0]
 ['Al' '100' '001' ... 13.0 1.0 1.0]
 ...
 ['Fe' '111' '009' ... 93.0 3.0 2.0]
 ['Fe' '111' '009' ... 97.0 3.0 1.0]
 ['Fe' '111' '009' ... 97.0 3.0 2.0]]


In [19]:
os.chdir('..')
os.getcwd()

'H:\\CNIDs_GB_area'

In [186]:
os.chdir('database/')
os.getcwd()

'C:\\Users\\hatayuki\\OneDrive - The University of Tokyo\\now_using\\database'

In [28]:
df_1 = pd.read_csv('bcc_cnid_list.csv',header = 0,index_col = 0)
df_1 = df_1.set_index(['element','axis','gbindex'])
print(df_1)

                         hkl_name  misorientation  cnidv1y       cnidv1z  \
element axis gbindex                                                       
Fe      100  1            <0 1 2>       53.130102    2.851  2.750000e-17   
             2            <0 3 1>       36.869898    2.851 -6.010000e-16   
             3            <0 2 3>       67.380135   -2.851 -3.160000e-16   
             4           <0 -1 5>       22.619865    2.851  1.240000e-16   
             5            <0 4 1>       28.072487    2.851  7.070000e-16   
...                           ...             ...      ...           ...   
W       111  90       <17 -4 -13>       26.007824   -2.740  1.730000e-16   
             91         <9 1 -10>       10.417438   -2.740  3.860000e-16   
             92        <8 11 -19>       49.582562    2.740  3.550000e-16   
             93         <8 3 -11>       30.590689   -2.740  3.120000e-16   
             94       <19 -5 -14>       29.409311   -2.740  1.630000e-16   

           

In [29]:
df_2 = pd.read_csv('fcc_cnid_list.csv',header = 0,index_col = 0)
df_2 = df_2.set_index(['element','axis','gbindex'])
print(df_2)

                         hkl_name  misorientation   cnidv1y       cnidv1z  \
element axis gbindex                                                        
Ag      100  1           <0 -1 3>       36.869898  4.072935 -4.320000e-16   
             2           <0 -2 1>       53.130102 -4.072935  2.090000e-16   
             3          <0 -5 -1>       22.619865 -4.072935  1.660000e-15   
             4           <0 -3 2>       67.380135 -4.072935 -2.460000e-16   
             5          <0 -3 -5>       61.927513  4.072935 -8.170000e-17   
...                           ...             ...       ...           ...   
Pt      111  90       <-4 -13 17>       26.007824  6.785087  4.680000e-16   
             91         <1 -10 9>       10.417438  6.785087  8.700000e-17   
             92       <-8 -11 19>       49.582562 -6.785087  9.300000e-15   
             93        <-8 -3 11>       30.590689  6.785087 -5.440000e-16   
             94       <-5 -14 19>       29.409311  6.785087 -4.880000e-15   

In [30]:
df_concat = pd.concat([df_1,df_2])
print(df_concat)
df_concat.to_csv('concat.csv')

                         hkl_name  misorientation   cnidv1y       cnidv1z  \
element axis gbindex                                                        
Fe      100  1            <0 1 2>       53.130102  2.851000  2.750000e-17   
             2            <0 3 1>       36.869898  2.851000 -6.010000e-16   
             3            <0 2 3>       67.380135 -2.851000 -3.160000e-16   
             4           <0 -1 5>       22.619865  2.851000  1.240000e-16   
             5            <0 4 1>       28.072487  2.851000  7.070000e-16   
...                           ...             ...       ...           ...   
Pt      111  90       <-4 -13 17>       26.007824  6.785087  4.680000e-16   
             91         <1 -10 9>       10.417438  6.785087  8.700000e-17   
             92       <-8 -11 19>       49.582562 -6.785087  9.300000e-15   
             93        <-8 -3 11>       30.590689  6.785087 -5.440000e-16   
             94       <-5 -14 19>       29.409311  6.785087 -4.880000e-15   

In [14]:
os.chdir('bcc/')
os.getcwd()

'E:\\CNIDs_GB_area_gbnum\\bcc'

In [16]:
# bcc_hkl_angle.csvを入れたbccファイルの中で実行
def make_bcc_cnid_list():
    df_bcc_hkl_angle = pd.read_csv('bcc_hkl_angle.csv',index_col = 0)
    bcc_hkl_angle = df_bcc_hkl_angle.values
    firstLoop = True
    for name in glob.glob('./**/*CNIDs', recursive=True):
        category_list = name.split('\\')[1:-1]
        CNIDs = np.loadtxt(os.path.abspath(name))
        gb_index = make_gb_index(len(CNIDs))
        CNIDs = np.hstack((bcc_hkl_angle, CNIDs))
        CNIDs = np.hstack((gb_index,CNIDs))
        category_list = np.tile(category_list,(len(CNIDs),1))
        CNIDs = np.hstack((category_list,CNIDs))
    #     CNIDs = np.hstack((CNIDs,hkl_angle))
        if firstLoop:
            CNIDs_list = CNIDs
            firstLoop = False
        else:
            CNIDs_list = np.vstack((CNIDs_list,CNIDs))
    return CNIDs_list

In [17]:
bcc_cnid_list = make_bcc_cnid_list()

In [18]:
df_bcc = pd.DataFrame(bcc_cnid_list)

In [19]:
df_bcc.to_csv('bcc_cnid_list.csv')

In [19]:
print(bcc_cnid_list)

[['Cr' '001' '<0 1 2>' ... 1.0 519.664284500724 364.0]
 ['Cr' '002' '<0 3 1>' ... 2.0 551.1872092663758 378.0]
 ['Cr' '003' '<0 2 3>' ... 1.0 418.96674042299844 294.0]
 ...
 ['W' '100' '<7 4 -11>' ... 2.0 546.0800687517375 312.0]
 ['W' '101' '<8 3 -11>' ... 1.0 1673.1002849932531 936.0]
 ['W' '102' '<19 -5 -14>' ... 2.0 965.9648999220941 552.0]]


In [183]:
df_bcc.head()

0    1         2          3         4    5         6          7         8   \
0  Cr  001   <0 1 2>  53.130102  2.880978 -0.0       0.0   6.442062  2.880978   
1  Cr  002   <0 3 1>  36.869898  2.880978 -0.0 -1.440489  -4.555226  2.880978   
2  Cr  003   <0 2 3>  67.380135 -2.880978  0.0      -0.0 -10.387513  2.880978   
3  Cr  004  <0 -1 5>  22.619865  2.880978  0.0 -1.440489  -7.345081  2.880978   
4  Cr  005   <0 4 1>  28.072487  2.880978  0.0       0.0  11.878576  2.880978   

          9          10    11   12   13  
0   6.442062  18.559439   5.0  1.0  1.0  
1   4.777561  13.123505   5.0  1.0  2.0  
2  10.387513  29.926196  13.0  1.0  1.0  
3      7.485  21.161016  13.0  1.0  2.0  
4  11.878576  34.221914  17.0  1.0  1.0

In [147]:
matrix.T[5]

array([53.13010235, 36.86989765, 67.38013505, ..., 42.10344887,
       30.5906886, 29.4093114], dtype=object)

In [20]:
#os.chdir('..')
os.getcwd()

'C:\\Users\\hatay\\calc\\bcc_GB_generator\\bcc'

In [7]:
# fcc_hkl_angle.csvを入れたfccファイルの中で実行
def make_fcc_cnid_list():
    df_fcc_hkl_angle = pd.read_csv('fcc_hkl_angle.csv',index_col = 0)
    fcc_hkl_angle = df_fcc_hkl_angle.values
    firstLoop = True
    for name in glob.glob('./**/*CNIDs', recursive=True):
        category_list = name.split('\\')[1:-1]
        CNIDs = np.loadtxt(os.path.abspath(name))
        gb_index = make_gb_index(len(CNIDs))
        CNIDs = np.hstack((fcc_hkl_angle, CNIDs))
        CNIDs = np.hstack((gb_index,CNIDs))
        category_list = np.tile(category_list,(len(CNIDs),1))
        CNIDs = np.hstack((category_list,CNIDs))
    #     CNIDs = np.hstack((CNIDs,hkl_angle))
        if firstLoop:
            CNIDs_list = CNIDs
            firstLoop = False
        else:
            CNIDs_list = np.vstack((CNIDs_list,CNIDs))
    return CNIDs_list

In [9]:
os.getcwd()

'H:\\CNIDs_GB_area\\fcc'

In [8]:
fcc_cnid_list = make_fcc_cnid_list()

In [10]:
fcc_cnid_list.shape

(752, 16)

In [11]:
df_fcc = pd.DataFrame(fcc_cnid_list)

In [12]:
df_fcc.to_csv('fcc_cnid_list.csv')

In [22]:
df_tot = pd.concat([df_bcc,df_fcc])

In [23]:
df_tot

0    1            2          3         4    5         6          7   \
0    Cr  001      <0 1 2>  53.130102  2.880978 -0.0       0.0   6.442062   
1    Cr  002      <0 3 1>  36.869898  2.880978 -0.0 -1.440489  -4.555226   
2    Cr  003      <0 2 3>  67.380135 -2.880978  0.0      -0.0 -10.387513   
3    Cr  004     <0 -1 5>  22.619865  2.880978  0.0 -1.440489  -7.345081   
4    Cr  005      <0 4 1>  28.072487  2.880978  0.0       0.0  11.878576   
..   ..  ...          ...        ...       ...  ...       ...        ...   
811  Pt  098  <-8 -11 19>  49.582562 -6.785087  0.0      -0.0 -26.424116   
812  Pt  099    <-1 -5 6>  17.896551  2.261696  0.0      -0.0   8.904304   
813  Pt  100   <-7 -4 11>  42.103449  6.785087  0.0       0.0  15.422707   
814  Pt  101   <-8 -3 11>  30.590689  6.785087 -0.0  2.261696 -15.750887   
815  Pt  102  <-5 -14 19>  29.409311  6.785087 -0.0      -0.0  27.281336   

           8          9           10    11   12   13          14     15  
0    2.880978   6.442062   18.559439   5.0  1.0  1.0  519.664285  364.0  
1    2.880978   4.777561   13.123505   5.0  1.0  2.0  551.187209  378.0  
2    2.880978  10.387513   29.926196  13.0  1.0  1.0   418.96674  294.0  
3    2.880978      7.485   21.161016  13.0  1.0  2.0  592.508446  420.0  
4    2.880978  11.878576   34.221914  17.0  1.0  1.0  479.106797  322.0  
..        ...        ...         ...   ...  ...  ...         ...    ...  
811  6.785087  26.424116  179.289913  91.0  3.0  2.0   537.86974  399.0  
812  2.261696   8.904304   20.138825  93.0  3.0  1.0  543.748272  405.0  
813  6.785087  15.422707  104.644404  93.0  3.0  2.0  627.866423  462.0  
814  6.785087  15.912438   106.87113  97.0  3.0  1.0  961.840169  711.0  
815  6.785087  27.281336  185.106227  97.0  3.0  2.0   555.31868  411.0  

[1530 rows x 16 columns]

In [24]:
df_tot.to_csv('cnid_list.csv')

In [28]:
os.chdir('OneDrive - The University of Tokyo/')

In [29]:
os.getcwd()

'C:\\Users\\hatayuki\\OneDrive - The University of Tokyo'

In [20]:
print(fcc_cnid_list)

[['Ag' '001' '<0 -1 3>' ... 1.0 524.5839122262878 340.0]
 ['Ag' '002' '<0 -2 1>' ... 2.0 556.4052624548651 390.0]
 ['Ag' '003' '<0 -5 -1>' ... 1.0 422.9330710979156 290.0]
 ...
 ['Pt' '100' '<-7 -4 11>' ... 2.0 627.8664228387325 462.0]
 ['Pt' '101' '<-8 -3 11>' ... 1.0 961.8401687782113 711.0]
 ['Pt' '102' '<-5 -14 19>' ... 2.0 555.3186803614955 411.0]]


In [173]:
print(len(CNIDs_list))

2754


In [127]:
a = np.array([[1,2,3,],
            [4,5,6,],
            [7,8,9,]])
#print(a.tolist()[:])
#a = a.reshape(len)
#a = np.array([a,a,a])
array_list = [a,a,a]
print(array_list)
array_list = np.array(array_list)
# 3次元行列を2次元行列に変換
print(array_list.reshape(int(array_list.size/len(array_list)),len(array_list)))
# array_list = [a.tolist(),a.tolist(),a.tolist()]
# print(len(array_list))

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [152]:
print(CNIDs_list.T[3][204])

001


In [83]:
os.getcwd()

'C:\\Users\\hatayuki\\OneDrive - The University of Tokyo\\now_using\\210905'

In [86]:
df = pd.read_csv('bcc_hkl_angle.csv', index_col= 0)

In [89]:
hkl_angle = df.values

In [90]:
print(hkl_angle)

[['<0 1 2>' 53.13010235]
 ['<0 3 1>' 36.86989765]
 ['<0 2 3>' 67.38013505]
 ['<0 -1 5>' 22.61986495]
 ['<0 4 1>' 28.07248694]
 ['<0 5 -3>' 61.92751306]
 ['<0 4 -3>' 73.73979529]
 ['<0 7 1>' 16.26020471]
 ['<0 5 2>' 43.60281897]
 ['<0 3 7>' 46.39718103]
 ['<0 6 1>' 18.92464442]
 ['<0 7 -5>' 71.07535558]
 ['<0 4 5>' 77.31961651]
 ['<0 -1 9>' 12.68038349]
 ['<0 7 2>' 31.8907918]
 ['<0 5 9>' 58.1092082]
 ['<0 6 -5>' 79.61114218]
 ['<0 11 1>' 10.38885782]
 ['<0 8 1>' 14.2500327]
 ['<0 9 -7>' 75.7499673]
 ['<0 8 3>' 41.11209044]
 ['<0 5 11>' 48.88790956]
 ['<0 6 7>' 81.20258929]
 ['<0 -1 13>' 8.79741071]
 ['<0 8 -5>' 64.01076642]
 ['<0 -3 13>' 25.98923358]
 ['<0 4 9>' 47.92497795]
 ['<0 -5 13>' 42.07502205]
 ['<-1 1 1>' 70.52877937]
 ['<1 -1 2>' 109.4712206]
 ['<-2 2 1>' 38.94244127]
 ['<1 -1 4>' 141.0575587]
 ['<1 -1 3>' 129.5211964]
 ['<-3 3 2>' 50.47880364]
 ['<2 -2 3>' 93.37228668]
 ['<-3 3 4>' 86.62771332]
 ['<-3 3 1>' 26.52535202]
 ['<1 -1 6>' 153.474648]
 ['<1 -1 5>' 148.4136619]
 ['<

In [27]:
os.chdir("C://Users//hatay//calc/fcc_GB_generator/fcc")
os.getcwd()

'C:\\Users\\hatay\\calc\\fcc_GB_generator\\fcc'

In [ ]:
for name in glob.glob("*.stgb"):
    category = name.split("_")[0]
    if category not in os.listdir("."):
        os.mkdir(f"{os.getcwd()}\\{category}")
    shutil.move(os.path.abspath(name),f"{os.getcwd()}\\{category}\\{name}")